Becoming a  Data Scientist
Learning linear algebra using numpy.
[ PART TWO ]
- # MATRIX

In [33]:
import numpy as np 


MATRIX ADDITION

In [34]:
A = np.array([[1,5,6],[1,8,9],[0,-1,6]])
B = np.array([[4,8,4],[1,0,5],[6,-8,4]])
A

array([[ 1,  5,  6],
       [ 1,  8,  9],
       [ 0, -1,  6]])

In [35]:
B

array([[ 4,  8,  4],
       [ 1,  0,  5],
       [ 6, -8,  4]])

In [36]:
A+B

array([[ 5, 13, 10],
       [ 2,  8, 14],
       [ 6, -9, 10]])

In [37]:
C = A+B

In [38]:
np.add(A,B)

array([[ 5, 13, 10],
       [ 2,  8, 14],
       [ 6, -9, 10]])

In [39]:
# casting the reults to a different type
np.add(A, B, dtype = np.float128)

array([[ 5., 13., 10.],
       [ 2.,  8., 14.],
       [ 6., -9., 10.]], dtype=float128)

MATRIX SUBRACTION

In [40]:
D = A-B
D

array([[-3, -3,  2],
       [ 0,  8,  4],
       [-6,  7,  2]])

In [41]:
np.subtract(A,B)

array([[-3, -3,  2],
       [ 0,  8,  4],
       [-6,  7,  2]])

In [42]:
np.subtract(A, B, dtype = np.float128)

array([[-3., -3.,  2.],
       [ 0.,  8.,  4.],
       [-6.,  7.,  2.]], dtype=float128)

MATRIX MULTIPLICATION(POINTWISE MULTIPLICATION)

In [43]:
E = A*B
E

array([[ 4, 40, 24],
       [ 1,  0, 45],
       [ 0,  8, 24]])

In [44]:
np.multiply(A, B)

array([[ 4, 40, 24],
       [ 1,  0, 45],
       [ 0,  8, 24]])

In [45]:
np.multiply(A, B, dtype=np.float128)

array([[ 4., 40., 24.],
       [ 1.,  0., 45.],
       [ 0.,  8., 24.]], dtype=float128)

MATRIX DIVISION (POINTWISE)

In [46]:
F = A/B
F

array([[0.25 , 0.625, 1.5  ],
       [1.   ,   inf, 1.8  ],
       [0.   , 0.125, 1.5  ]])

In [47]:
np.divide(A, B)

array([[0.25 , 0.625, 1.5  ],
       [1.   ,   inf, 1.8  ],
       [0.   , 0.125, 1.5  ]])

In [48]:
np.divide(A, B, dtype=np.float128)

array([[0.25 , 0.625, 1.5  ],
       [1.   ,   inf, 1.8  ],
       [0.   , 0.125, 1.5  ]], dtype=float128)

In [49]:
np.int16(F)

array([[0, 0, 1],
       [1, 0, 1],
       [0, 0, 1]], dtype=int16)

### MATRIX PRODUCTS

In [50]:
np.matmul(A, B)

array([[ 45, -40,  53],
       [ 66, -64,  80],
       [ 35, -48,  19]])

$$C = AB$$

$$C_{ij} = \sum_{k=1}^N A_{ik} B_{kj}$$

In [54]:
G = np.array([[1,2,3,4],[2,5,6,8],[1,2,4,10]])
G

array([[ 1,  2,  3,  4],
       [ 2,  5,  6,  8],
       [ 1,  2,  4, 10]])

In [57]:
# you can multipy (A or B) by C but not G by (B or A)
np.matmul(A, G)

array([[ 17,  39,  57, 104],
       [ 26,  60,  87, 158],
       [  4,   7,  18,  52]])

In [58]:
np.matmul(B, G)

array([[ 24,  56,  76, 120],
       [  6,  12,  23,  54],
       [ -6, -20, -14,   0]])

In [60]:
# uncomment line  to test
# np.matmul(G, A) 

In [61]:
# Fix by using transpose
np.matmul(G.transpose(), A )

array([[  3,  20,  30],
       [  7,  48,  69],
       [  9,  59,  96],
       [ 12,  74, 156]])

In [64]:
a  = A[:, 0]
a

array([1, 1, 0])

In [65]:
b = B[:,0]
b

array([4, 1, 6])

In [66]:
np.matmul(a, b)

5

In [67]:
np.dot(a,b)

5

$$<a,b> = a^T b = \sum_{i=1}^n a_i b_i$$

In [68]:
np.inner(a,b)

5

In [70]:
np.tensordot(A,B)

array(146)

In [72]:
 >>> a = np.arange(60.).reshape(3,4,5)
 >>> b = np.arange(24.).reshape(4,3,2)
 np.tensordot(a,b, axes=([1,0],[0,1]))

array([[4400., 4730.],
       [4532., 4874.],
       [4664., 5018.],
       [4796., 5162.],
       [4928., 5306.]])

In [74]:
# matrix power
print(A)
np.linalg.matrix_power(A, 10)

[[ 1  5  6]
 [ 1  8  9]
 [ 0 -1  6]]


array([[  -74112867,  -562232043,  -696061917],
       [ -113084721,  -860918571, -1044890766],
       [     531927,   115744356,  -626770224]])

In [76]:
# matrix exponantiation 
np.matmul(A, A)

array([[  6,  39,  87],
       [  9,  60, 132],
       [ -1, -14,  27]])

$$C = A \otimes B$$

In [78]:
H = np.kron(A,B)
H

array([[  4,   8,   4,  20,  40,  20,  24,  48,  24],
       [  1,   0,   5,   5,   0,  25,   6,   0,  30],
       [  6,  -8,   4,  30, -40,  20,  36, -48,  24],
       [  4,   8,   4,  32,  64,  32,  36,  72,  36],
       [  1,   0,   5,   8,   0,  40,   9,   0,  45],
       [  6,  -8,   4,  48, -64,  32,  54, -72,  36],
       [  0,   0,   0,  -4,  -8,  -4,  24,  48,  24],
       [  0,   0,   0,  -1,   0,  -5,   6,   0,  30],
       [  0,   0,   0,  -6,   8,  -4,  36, -48,  24]])

### MATRIX DECOMPOSITION
##### Cholesky decomposition

In [83]:
I = np.linalg.cholesky(A)
I

array([[ 1.        ,  0.        ,  0.        ],
       [ 1.        ,  2.64575131,  0.        ],
       [ 0.        , -0.37796447,  2.42015348]])

In [84]:
np.matmul(I, I.transpose())

array([[ 1.,  1.,  0.],
       [ 1.,  8., -1.],
       [ 0., -1.,  6.]])

In [85]:
A

array([[ 1,  5,  6],
       [ 1,  8,  9],
       [ 0, -1,  6]])

In [88]:
J = np.array([[1,-2j],[2j,5]])
J

array([[ 1.+0.j, -0.-2.j],
       [ 0.+2.j,  5.+0.j]])

In [90]:
K = np.linalg.cholesky(J)
np.matmul(K, K.T.conj())

array([[1.+0.j, 0.-2.j],
       [0.+2.j, 5.+0.j]])

In [91]:
A.T

array([[ 1,  1,  0],
       [ 5,  8, -1],
       [ 6,  9,  6]])

##### QR Decomposition  $$A = QR $$

In [98]:
L = np.linalg.qr(A)[0]
M = np.linalg.qr(A)[1]
(d,e) = np.linalg.eig(A)
np.matmul(L,M)

array([[ 1.,  5.,  6.],
       [ 1.,  8.,  9.],
       [ 0., -1.,  6.]])