Becoming a  Data Scientist
Learning linear algebra using numpy.
[ PART ONE ]

In [1]:
import numpy as np

a = np.array([145,24,33,44,65])
a
type(a)

numpy.ndarray

Indexing elements in a numpy array

In [2]:
a[2:4]

array([33, 44])

Getting a dimmension of an arrays

In [3]:
a.shape

(5,)

In [10]:
b = np.array([[564,65,65,74],[654,65,4,654],[6,5,78,5],[68,546,54,454],[87,45,65,456],[4,478,114,45],[45,369,6,47]])
b

array([[564,  65,  65,  74],
       [654,  65,   4, 654],
       [  6,   5,  78,   5],
       [ 68, 546,  54, 454],
       [ 87,  45,  65, 456],
       [  4, 478, 114,  45],
       [ 45, 369,   6,  47]])

In [11]:
b.shape

(7, 4)

In [12]:
b[2:4]

array([[  6,   5,  78,   5],
       [ 68, 546,  54, 454]])

In [13]:
b[1:2,3:]

array([[654]])

In [20]:
C = np.eye(5)

In [21]:
C

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [22]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [23]:
np.ones((6,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [25]:
c = np.full((4,6),10)
c

array([[10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10]])

In [27]:
d = np.random.random((2,2))
d

array([[0.0718908 , 0.07939577],
       [0.99000322, 0.3938062 ]])

In [28]:
np.random.random()

0.03336587702199756

In [29]:
e = np.random.random((10000,20))
e

array([[0.09776277, 0.80141115, 0.91502485, ..., 0.64676808, 0.33217207,
        0.45606664],
       [0.47630897, 0.1106279 , 0.59567676, ..., 0.53566847, 0.88723466,
        0.42385898],
       [0.40442997, 0.35886901, 0.15176712, ..., 0.83736939, 0.2621538 ,
        0.71463154],
       ...,
       [0.45604044, 0.74542952, 0.12756856, ..., 0.14212579, 0.11726483,
        0.30451214],
       [0.79898066, 0.81912323, 0.16588651, ..., 0.5575386 , 0.36469445,
        0.06458753],
       [0.38571069, 0.8225302 , 0.46567981, ..., 0.26213677, 0.54837038,
        0.48629764]])

In [30]:
np.mean(e)

0.4985230610187105

$$Var(x) = E(x^2) - E^2(x) = \int_{0}^1 x^2 \ dx - \frac1 4 = \frac1 3 - \frac1 4 = \frac1{12}$$ 

In [34]:
np.std(e)**2

0.08304333786444805

In [35]:
1/12

0.08333333333333333

In [40]:
print(a.dtype)
print(b.dtype)
print(c.dtype)
print(C.dtype)
print(e.dtype)

int64
int64
int64
float64
float64
