Becoming a  Data Scientist
Learning linear algebra using numpy.
[ PART TWO ]
- MATRIX

In [9]:
import numpy as np 


MATRIX ADDITION

In [10]:
A = np.array([[1,5,6],[1,8,9],[0,-1,6]])
B = np.array([[4,8,4],[1,0,5],[6,-8,4]])
A

array([[ 1,  5,  6],
       [ 1,  8,  9],
       [ 0, -1,  6]])

In [11]:
B

array([[ 4,  8,  4],
       [ 1,  0,  5],
       [ 6, -8,  4]])

In [12]:
A+B

array([[ 5, 13, 10],
       [ 2,  8, 14],
       [ 6, -9, 10]])

In [13]:
C = A+B

In [14]:
np.add(A,B)

array([[ 5, 13, 10],
       [ 2,  8, 14],
       [ 6, -9, 10]])

In [15]:
# casting the reults to a different type
np.add(A, B, dtype = np.float128)

array([[ 5., 13., 10.],
       [ 2.,  8., 14.],
       [ 6., -9., 10.]], dtype=float128)

MATRIX SUBRACTION

In [17]:
D = A-B
D

array([[-3, -3,  2],
       [ 0,  8,  4],
       [-6,  7,  2]])

In [18]:
np.subtract(A,B)

array([[-3, -3,  2],
       [ 0,  8,  4],
       [-6,  7,  2]])

In [19]:
np.subtract(A, B, dtype = np.float64)

array([[-3., -3.,  2.],
       [ 0.,  8.,  4.],
       [-6.,  7.,  2.]])

MATRIX MULTIPLICATION(POINTWISE MULTIPLICATION)