Becoming a  Data Scientist
Learning linear algebra using numpy.
[ PART TWO ]
- # MATRIX

In [33]:
import numpy as np 


MATRIX ADDITION

In [34]:
A = np.array([[1,5,6],[1,8,9],[0,-1,6]])
B = np.array([[4,8,4],[1,0,5],[6,-8,4]])
A

array([[ 1,  5,  6],
       [ 1,  8,  9],
       [ 0, -1,  6]])

In [35]:
B

array([[ 4,  8,  4],
       [ 1,  0,  5],
       [ 6, -8,  4]])

In [36]:
A+B

array([[ 5, 13, 10],
       [ 2,  8, 14],
       [ 6, -9, 10]])

In [37]:
C = A+B

In [38]:
np.add(A,B)

array([[ 5, 13, 10],
       [ 2,  8, 14],
       [ 6, -9, 10]])

In [39]:
# casting the reults to a different type
np.add(A, B, dtype = np.float128)

array([[ 5., 13., 10.],
       [ 2.,  8., 14.],
       [ 6., -9., 10.]], dtype=float128)

MATRIX SUBRACTION

In [40]:
D = A-B
D

array([[-3, -3,  2],
       [ 0,  8,  4],
       [-6,  7,  2]])

In [41]:
np.subtract(A,B)

array([[-3, -3,  2],
       [ 0,  8,  4],
       [-6,  7,  2]])

In [42]:
np.subtract(A, B, dtype = np.float128)

array([[-3., -3.,  2.],
       [ 0.,  8.,  4.],
       [-6.,  7.,  2.]], dtype=float128)

MATRIX MULTIPLICATION(POINTWISE MULTIPLICATION)

In [43]:
E = A*B
E

array([[ 4, 40, 24],
       [ 1,  0, 45],
       [ 0,  8, 24]])

In [44]:
np.multiply(A, B)

array([[ 4, 40, 24],
       [ 1,  0, 45],
       [ 0,  8, 24]])

In [45]:
np.multiply(A, B, dtype=np.float128)

array([[ 4., 40., 24.],
       [ 1.,  0., 45.],
       [ 0.,  8., 24.]], dtype=float128)

MATRIX DIVISION (POINTWISE)

In [46]:
F = A/B
F

array([[0.25 , 0.625, 1.5  ],
       [1.   ,   inf, 1.8  ],
       [0.   , 0.125, 1.5  ]])

In [47]:
np.divide(A, B)

array([[0.25 , 0.625, 1.5  ],
       [1.   ,   inf, 1.8  ],
       [0.   , 0.125, 1.5  ]])

In [48]:
np.divide(A, B, dtype=np.float128)

array([[0.25 , 0.625, 1.5  ],
       [1.   ,   inf, 1.8  ],
       [0.   , 0.125, 1.5  ]], dtype=float128)

In [49]:
np.int16(F)

array([[0, 0, 1],
       [1, 0, 1],
       [0, 0, 1]], dtype=int16)

### MATRIX PRODUCTS