Becoming a  Data Scientist
Learning linear algebra using numpy.

In [1]:
import numpy as np

a = np.array([145,24,33,44,65])
a
type(a)

numpy.ndarray

Indexing elements in a numpy array

In [2]:
a[2:4]

array([33, 44])

Getting a dimmension of an arrays

In [3]:
a.shape

(5,)

In [10]:
b = np.array([[564,65,65,74],[654,65,4,654],[6,5,78,5],[68,546,54,454],[87,45,65,456],[4,478,114,45],[45,369,6,47]])
b

array([[564,  65,  65,  74],
       [654,  65,   4, 654],
       [  6,   5,  78,   5],
       [ 68, 546,  54, 454],
       [ 87,  45,  65, 456],
       [  4, 478, 114,  45],
       [ 45, 369,   6,  47]])

In [11]:
b.shape

(7, 4)

In [12]:
b[2:4]

array([[  6,   5,  78,   5],
       [ 68, 546,  54, 454]])

In [13]:
b[1:2,3:]

array([[654]])

In [20]:
C = np.eye(5)

In [21]:
C

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [22]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [23]:
np.ones((6,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])