Becoming a  Data Scientist
Learning linear algebra using numpy.
[ PART TWO ]
- # MATRIX

In [33]:
import numpy as np 


MATRIX ADDITION

In [34]:
A = np.array([[1,5,6],[1,8,9],[0,-1,6]])
B = np.array([[4,8,4],[1,0,5],[6,-8,4]])
A

array([[ 1,  5,  6],
       [ 1,  8,  9],
       [ 0, -1,  6]])

In [35]:
B

array([[ 4,  8,  4],
       [ 1,  0,  5],
       [ 6, -8,  4]])

In [36]:
A+B

array([[ 5, 13, 10],
       [ 2,  8, 14],
       [ 6, -9, 10]])

In [37]:
C = A+B

In [38]:
np.add(A,B)

array([[ 5, 13, 10],
       [ 2,  8, 14],
       [ 6, -9, 10]])

In [39]:
# casting the reults to a different type
np.add(A, B, dtype = np.float128)

array([[ 5., 13., 10.],
       [ 2.,  8., 14.],
       [ 6., -9., 10.]], dtype=float128)

MATRIX SUBRACTION

In [40]:
D = A-B
D

array([[-3, -3,  2],
       [ 0,  8,  4],
       [-6,  7,  2]])

In [41]:
np.subtract(A,B)

array([[-3, -3,  2],
       [ 0,  8,  4],
       [-6,  7,  2]])

In [42]:
np.subtract(A, B, dtype = np.float128)

array([[-3., -3.,  2.],
       [ 0.,  8.,  4.],
       [-6.,  7.,  2.]], dtype=float128)

MATRIX MULTIPLICATION(POINTWISE MULTIPLICATION)

In [43]:
E = A*B
E

array([[ 4, 40, 24],
       [ 1,  0, 45],
       [ 0,  8, 24]])

In [44]:
np.multiply(A, B)

array([[ 4, 40, 24],
       [ 1,  0, 45],
       [ 0,  8, 24]])

In [45]:
np.multiply(A, B, dtype=np.float128)

array([[ 4., 40., 24.],
       [ 1.,  0., 45.],
       [ 0.,  8., 24.]], dtype=float128)

MATRIX DIVISION (POINTWISE)

In [46]:
F = A/B
F

array([[0.25 , 0.625, 1.5  ],
       [1.   ,   inf, 1.8  ],
       [0.   , 0.125, 1.5  ]])

In [47]:
np.divide(A, B)

array([[0.25 , 0.625, 1.5  ],
       [1.   ,   inf, 1.8  ],
       [0.   , 0.125, 1.5  ]])

In [48]:
np.divide(A, B, dtype=np.float128)

array([[0.25 , 0.625, 1.5  ],
       [1.   ,   inf, 1.8  ],
       [0.   , 0.125, 1.5  ]], dtype=float128)

In [49]:
np.int16(F)

array([[0, 0, 1],
       [1, 0, 1],
       [0, 0, 1]], dtype=int16)

### MATRIX PRODUCTS

In [50]:
np.matmul(A, B)

array([[ 45, -40,  53],
       [ 66, -64,  80],
       [ 35, -48,  19]])

$$C = AB$$

$$C_{ij} = \sum_{k=1}^N A_{ik} B_{kj}$$

In [54]:
G = np.array([[1,2,3,4],[2,5,6,8],[1,2,4,10]])
G

array([[ 1,  2,  3,  4],
       [ 2,  5,  6,  8],
       [ 1,  2,  4, 10]])

In [57]:
# you can multipy (A or B) by C but not G by (B or A)
np.matmul(A, G)

array([[ 17,  39,  57, 104],
       [ 26,  60,  87, 158],
       [  4,   7,  18,  52]])

In [58]:
np.matmul(B, G)

array([[ 24,  56,  76, 120],
       [  6,  12,  23,  54],
       [ -6, -20, -14,   0]])

In [60]:
# uncomment line  to test
# np.matmul(G, A) 

In [61]:
# Fix by using transpose
np.matmul(G.transpose(), A )

array([[  3,  20,  30],
       [  7,  48,  69],
       [  9,  59,  96],
       [ 12,  74, 156]])

In [64]:
a  = A[:, 0]
a

array([1, 1, 0])

In [65]:
b = B[:,0]
b

array([4, 1, 6])

In [66]:
np.matmul(a, b)

5

$$<a,b> = a^T b = \sum_{i=1}^n a_i b_i$$